### ISSUE TITLE
PHPIPAM 1.1.010 Strict mode not working on sub folders.

### ISSUE THREAD

**Issue by bitking** [redhat-cip/phpipam#11]
Hi there,

When i make a folder in my root and create subnets inside that folder i can make overlapping ranges. When i make a subnet ranger in the root which overlaps i get a error and cannot do that which is ofcourse good.

Can you please fix this?

Thanks!

**Comment by ghantoos** [comment]
This fork is not maintained anymore. Sorry for that.
