### ISSUE TITLE
Manual Sorting

### ISSUE THREAD

**Issue by buzzsurfr** [redhat-cip/phpipam#2]
There is no option to sort sections, and I think that there should be an option to sort subnets and sections manually.  The easiest way that comes to mind is tying in with the responsive theme and on the Section/Subnet screen use the ![image](https://f.cloud.github.com/assets/2147011/866830/3f6d01d8-f6b7-11e2-9346-c13ab17880ed.png) (arrow-crosshair) icon and the _draggable_ property to move subnets and use a hidden variable to reorder them.

**EDIT:** I see the pages in 0.86 rev001--I will work on the draggable property in the sort screen.  Also, nice to see someone finally make a worthwhile utility for networking.  I have been in your same situation for awhile.

**Comment by buzzsurfr** [comment]
Also, I plan on providing some PRs to help, I just need to familiarize myself with the code.

**Comment by cocotton** [comment]
Hello buzzsurfr,

Thank you for your input. There might be a little bit of confusion, but this project is actually are fork from : http://sourceforge.net/projects/phpipam/?source=directory which is the original.

As for sorting the sections, you will need to go on the Administration page and then on the Section Management page. From there, you'll be able to sort the sections by clicking the "section order" button. 

Cheers!
